resources:
- ./resources/upstream.yml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: argocd

configMapGenerator:
- name: argocd-dashboard-cm
  files:
    - dashboard.json
patchesJson6902:
- target:
    name: prometheus-operator-grafana
    namespace: prometheus-operator
    group: 
    version: v1
    kind: Secret
  path: overlays/prometheus-operator-grafana-secret.yaml
    
patchesStrategicMerge:
- overlays/prometheus-operator-grafana-cm.yaml
