apiVersion: v1
kind: ConfigMap

metadata:
  name: coredns
  namespace: sksat-system

data:
  Corefile: |
    .:53 {
        forward . tls://1.1.1.1 tls://1.0.0.1 1.1.1.1 1.0.0.1 8.8.8.8 {
            policy sequential
            tls_servername clouflare-dns.com
            health_check 5s
        }

        metadata
        log . "{remote}:{port} - {>id} {type} {class} {name} {proto} {size} {>do} {>bufsize} {rcode} {>rflags} {rsize} {duration} {/forward/upstream}"

        prometheus :9153
        cache 30
        errors
        loop
        reload
        loadbalance
    }
